# -*- coding: utf-8 -*-
#
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionIdentityProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1c\x45xtensionIdentityProto.proto\x12\x1forg.opensearch.extensions.proto"%\n\x11\x45xtensionIdentity\x12\x10\n\x08uniqueId\x18\x01 \x01(\tB\x18\x42\x16\x45xtensionIdentityProtob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ExtensionIdentityProto_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\026ExtensionIdentityProto"
    _globals["_EXTENSIONIDENTITY"]._serialized_start = 65
    _globals["_EXTENSIONIDENTITY"]._serialized_end = 102
# @@protoc_insertion_point(module_scope)
