# -*- coding: utf-8 -*-
#
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HandleTransportRequestProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!HandleTransportRequestProto.proto\x12\x1forg.opensearch.extensions.proto"A\n\x19\x45xtensionTransportMessage\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x14\n\x0crequestBytes\x18\x02 \x01(\x0c\x42 B\x1e\x45xtensionTransportMessageProtob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "HandleTransportRequestProto_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\036ExtensionTransportMessageProto"
    _globals["_EXTENSIONTRANSPORTMESSAGE"]._serialized_start = 70
    _globals["_EXTENSIONTRANSPORTMESSAGE"]._serialized_end = 135
# @@protoc_insertion_point(module_scope)
