# -*- coding: utf-8 -*-
#
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterTransportActionsProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ExtensionIdentityProto_pb2 as ExtensionIdentityProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#RegisterTransportActionsProto.proto\x12\x1forg.opensearch.extensions.proto\x1a\x1c\x45xtensionIdentityProto.proto"z\n\x18RegisterTransportActions\x12\x44\n\x08identity\x18\x01 \x01(\x0b\x32\x32.org.opensearch.extensions.proto.ExtensionIdentity\x12\x18\n\x10transportActions\x18\x02 \x03(\tB\x1f\x42\x1dRegisterTransportActionsProtob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "RegisterTransportActionsProto_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\035RegisterTransportActionsProto"
    _globals["_REGISTERTRANSPORTACTIONS"]._serialized_start = 102
    _globals["_REGISTERTRANSPORTACTIONS"]._serialized_end = 224
# @@protoc_insertion_point(module_scope)
