---
name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.9'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.5.1'
      - run: poetry install
      - run: poetry run isort --check .
      - run: poetry run flake8 .
      - run: poetry run mypy .
      - run: |
          poetry run licenseheaders -t LICENSE_HEADER.txt -E .py
          git diff --name-only .
          git diff --quiet --name-only . || exit -1 
